name: test_coverage

on: [push]


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python utils/downgrade_patch.py -d .
          pip install -e .
          pip install -r requirements_test.txt

      - name: build coverage file
        # run: |
        #   pytest --cache-clear --cov-fail-under=100 --cov=df_engine tests/ > pytest-coverage.txt
        run: |
          pytest --cache-clear --cov-fail-under=100 --cov=df_engine tests/ > pytest-coverage.txt
